version: '3.8'

services:
  wtw:
    image: netplexflix/wtwp:latest
    container_name: wtwp
    restart: unless-stopped
    ports:
      - "3000:3000" #change port by using "xxxx:3000"
    volumes:
      - ${WTW_DATA_PATH:-./data}:/app/data
    environment:
      - NODE_ENV=production
      - DATA_PATH=/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3